name: build deployment
on:
  push:
    branches:
      - '*'
jobs:
  display-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Display branch name
      run: |
        echo "Current branch: ${GITHUB_REF##*/}"

    - name: Set Dynamic Variable
      run: echo "MY_DYNAMIC_VARIABLE=${{GITHUB_REF##*/}}" >> $GITHUB_ENV

    - name: Use Dynamic Variable
      run: echo "The value of MY_DYNAMIC_VARIABLE is $MY_DYNAMIC_VARIABLE"
      
  #building .war file in cloud
  build:
    runs-on: ubuntu-latest
    needs: display-branch
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        pwd
        chmod +x mvnw
        ./mvnw clean package -Dmaven.test.skip
    #uploading war file into artifact - later it can be used in next job
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: output-war
        path: target/testrunner-0.0.1-SNAPSHOT.war
  #self-hosted job - which will run in windows power shell
  local-job:
    runs-on: self-hosted
    #will work only if previous build job - success
    needs: build
    steps:
      - name: example
        run: echo "Hello runner test"
      #downloading artifact from previous build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: output-war
          #storing .war file into local system folder
          path: C:\prajoth\test-runner-service-wrapper
      #checking pressence of windows service
      - name: Check windows service exist or not
        run: |
          #name of service - also same used in winsw wrapper xml
          $serviceName = "TestRunner"
          $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
          if ($service){
            #service available
            if ($service.Status -eq 'Running') {
                #service running - so stopping
                C:\prajoth\test-runner-service-wrapper\test-runner-service-wrapper.exe stop
                #wait for 15 sec to complete stop - getting warning if not add this
                sleep 15
            }
            #service uninstall
            C:\prajoth\test-runner-service-wrapper\test-runner-service-wrapper.exe uninstall
          }
          #service install
          C:\prajoth\test-runner-service-wrapper\test-runner-service-wrapper.exe install
          #service start
          C:\prajoth\test-runner-service-wrapper\test-runner-service-wrapper.exe start
          
        
