name: build deployment
on:
  push:
    branches:
     - master
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        pwd
        chmod +x mvnw
        ./mvnw clean package -Dmaven.test.skip
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: output-war
        path: target/testrunner-0.0.1-SNAPSHOT.war
  local-job:
    runs-on: self-hosted
    needs: build
    steps:
      - name: example
        run: echo "Hello runner"
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: output-war
          path: C:\prajoth\test-runner-service-wrapper
      - name: Check service exist or not
        run: |
          $serviceName = "TestRunner"
          $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue
          if ($service){
            echo "service available"
            C:\prajoth\test-runner-service-wrapper\test-runner-service-wrapper.exe restart
          }else{
            echo "NotAvailable"
            C:\prajoth\test-runner-service-wrapper\test-runner-service-wrapper.exe install
            C:\prajoth\test-runner-service-wrapper\test-runner-service-wrapper.exe start
          }
          
        
