name: Deploy to Staging

on:
  workflow_run:
    workflows: ["build deployment"] # Name of the build workflow
    types: [completed]

jobs:
  deploy:
    runs-on: [self-hosted, staging-deploy] # Target self-hosted runner with specific labels
    steps:
      - name: example
        run: echo "Hello Wo"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output data
          path: target/**
