on:
  push:
    branches:
     - master
     - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up local JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'jdkFile'
        jdkFile: 'C:\Program Files\Java\jdk-24'
        java-version: '24'
    - name: Build with Maven
      run: |
        pwd
        chmod +x mvnw
        ./mvnw clean package -Dmaven.test.skip
