on:
  push:
    branches:
     - master
     - main

jobs:
  local-job:
    runs-on: self-hosted
    steps:
      - name: example
        run: echo "Hello W"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
        pwd
        cd runner-test
        pwd
        chmod +x mvnw
        ./mvnw clean package -Dmaven.test.skip
