on:
  push:
    branches:
     - master
     - main

jobs:
  local-job:
    runs-on: self-hosted
    steps:
      - name: example
        run: echo "Hello"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        pwd
        chmod +x mvnw
        ./mvnw clean package
        
    - name: Move final build
      run: |
        pwd      
        pwd
        mkdir build_output
        pwd
        ls
        chmod 777 build_output
        chmod 777 target
        pwd
        ls
        pwd
        mv target/runner-test.war build_output/runner-test.war
        cd build_output
        pwd
        ls
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
          name: runner-test-binary
          path: runner-test/build_output
