on:
  push:
    branches:
     - master
     - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up local JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Build with Maven
      run: |
        pwd
        chmod +x mvnw
        ./mvnw clean package -Dmaven.test.skip
